# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-vapor-extension}
  s.version = "2.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jim Gay}]
  s.date = %q{2011-09-15}
  s.description = %q{Provides an interface to redirect URLs in RadiantCMS}
  s.email = %q{jim@saturnflyer.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "HELP_admin.md",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/flow_meters_controller.rb",
    "app/helpers/admin/flow_meters_helper.rb",
    "app/helpers/admin/page_node_alterations_helper.rb",
    "app/metal/vapor_flow.rb",
    "app/models/flow_meter.rb",
    "app/views/admin/flow_meters/index.html.haml",
    "app/views/admin/help/_slug_redirect.html.haml",
    "app/views/admin/pages/_vapor_details.html.haml",
    "config/routes.rb",
    "db/migrate/001_create_flow_meters.rb",
    "lib/page_vapor.rb",
    "lib/radiant-vapor-extension.rb",
    "lib/tasks/vapor_extension_tasks.rake",
    "lib/vaporizer.rb",
    "spec/controllers/admin/flow_meters_controller_spec.rb",
    "spec/metal/vapor_flow_spec.rb",
    "spec/models/flow_meter_spec.rb",
    "spec/models/page_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "test/test_helper.rb",
    "vapor_extension.rb"
  ]
  s.homepage = %q{http://github.com/saturnflyer/radiant-vapor-extension}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Provides an interface to redirect URLs in RadiantCMS}
  s.test_files = [
    "spec/controllers/admin/flow_meters_controller_spec.rb",
    "spec/metal/vapor_flow_spec.rb",
    "spec/models/flow_meter_spec.rb",
    "spec/models/page_spec.rb",
    "spec/spec_helper.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<radiant>, [">= 0"])
    else
      s.add_dependency(%q<radiant>, [">= 0"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0"])
  end
end

